development:
  url: "https://www.sandbox.paypal.com/cgi-bin/webscr?"
  seller: seller_1316033726_biz@gmail.com
  
test:
  url: "https://www.sandbox.paypal.com/cgi-bin/webscr?"
  seller: seller_1316033726_biz@gmail.com
    
production:
  url: "https://www.sandbox.paypal.com/cgi-bin/webscr?"
  seller_id: seller_1316033726_biz@gmail.com